language: python

git:
  depth: 5000

dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

# Required to run the respective python env in tox
install: pip install tox-travis

# command to run tests
script:
  - tox
  - tox -e pep8

