name: pypi
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy PyPI
    runs-on: ubuntu-latest
    env:
      FLIT_USERNAME: '__token__'
      FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install flit
          python -m flit publish

